config/routes.rb
Rails.application.routes.draw do
  resources :codes
  resources :rooms do
    resources :prompts
  end
  resources :contacts do
    resources :contact_comments
    member do
      get 'add_notes'
      patch :hide
    end
  end
  devise_for :users
  resources :addresses do
    resources :violations, shallow: true do
      resources :citations, shallow: true do
        resources :citation_comments
      end
      member do
        get :extend_deadline
        patch :update_deadline
        get :units
      end
      patch :resolve, on: :member
      patch :update, on: :member
      get :generate_report, on: :member
      resources :violation_comments
      collection do
        get :export_csv
      end
    end
    resources :comments
    resources :concerns, only: [:create, :edit, :update]
    resources :units, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      member do
        get 'new_unit_business', to: 'businesses#new_unit_business'
        get 'all_unit_comments'
        get 'all_unit_violations'
        get 'all_unit_citations'
        get 'all_unit_inspections'
        get 'all_unit_complaints'
        get 'manage_contacts'
        post 'manage_contacts'
        delete 'remove_contact'
        get :set_potentially_vacant
        get :set_vacant
        get :set_occupied
      end
    end
    resources :inspections do
      member do
        get 'conduct'
        get 'schedule'
        post 'save_and_redirect_to_area_new'
        get 'create_business_license'
        get 'create_single_family_license'
        get 'create_multifamily_license'
        get 'create_permit'
      end
      resources :areas do
        resources :observations, only: [:create, :edit, :update]
      end
      resources :inspection_comments
      resources :licenses, except: [:index]
    end
    resources :businesses, except: [:index, :new_business]
    member do
      get 'manage_contacts'
      post 'manage_contacts'
      delete 'remove_contact'
      get 'address_name'
      get 'all_address_violations'
      get 'all_address_comments'
      get 'all_address_citations'
      get 'all_address_inspections'
      get 'all_address_complaints'
      get 'add_aka'
      get :set_potentially_vacant
      get :set_vacant
      get :set_occupied
      get :set_registered
    end
    collection do
      get :potentially_vacant
      get :vacant
    end
  end

  resources :licenses do
    get 'email_license' => 'licenses#email_license'
    get 'download_license' => 'licenses#download_license'
    member do
      put 'sent_today' => 'licenses#sent_today' 
      put 'not_sent' => 'licenses#not_sent'
      put 'paid' => 'licenses#paid'
      put 'not_paid' => 'licenses#not_paid'
      get 'generate_business'
      get 'generate_single_family'
    end
  end

  resources :permits do
    member do
      put 'sent' => 'permits#sent'
      put 'revoked' => 'permits#revoked'
      put 'paid' => 'permits#paid'
    end
  end

  get 'all_inspections' => 'inspections#all_inspections'
  get 'my_inspections' => 'inspections#my_inspections'
  get 'my_unscheduled_inspections' => 'inspections#my_unscheduled_inspections'
  get 'all_complaints' => 'inspections#all_complaints'
  get 'my_complaints' => 'inspections#my_complaints'
  get 'all_violations' => 'violations#violist'
  get 'my_violations' => 'addresses#my_violations'
  get 'helpful' => 'static#helpful'
  get 'businesses' => 'businesses#index'
  patch 'mark_reviewed/:id' => 'static#mark_reviewed', as: 'mark_reviewed'
  get 'design_test' => 'static#design_test'
  get 'new_business' => 'businesses#new_business'
  post 'new_business' => 'businesses#create_business'
  get 'new_complaint' => 'inspections#new_complaint'
  post 'new_complaint' => 'inspections#create_complaint'
  get 'new_permit_inspection' => 'inspections#new_permit_inspection'
  post 'new_permit_inspection' => 'inspections#create_permit_inspection'
  get 'new_license_inspection' => 'inspections#new_license_inspection'
  post 'new_license_inspection' => 'inspections#create_license_inspection'
  get 'unassigned_inspections' => 'inspections#unassigned_inspections'
  get 'assign_inspection/:id' => 'inspections#assign_inspection', as: 'assign_inspection'
  patch 'update_inspector/:id' => 'inspections#update_inspector', as: 'update_inspector'
  get 'inspection_calendar' => 'inspections#inspection_calendar'
  get 'new_business_violation/:business_id' => 'violations#new_business_violation', as: 'new_business_violation'
  get 'all_licenses' => 'licenses#index'
  get 'all_permits' => 'permits#index'
  get 'map' => 'static#map'
  get 'export_violations' => 'violations#export_csv'
  get 'export_property_csv' => 'violations#export_property_csv'
  patch 'inspections/:id/mark_as_paid', to: 'inspections#mark_as_paid', as: :mark_as_paid
  patch 'inspections/:id/mark_as_not_paid', to: 'inspections#mark_as_not_paid', as: :mark_as_not_paid
  post 'create_unit' => 'inspections#create_unit'

  resources :users, only: [:index, :show, :edit, :update]
  resources :notifications do
    member do
      patch :mark_as_read
    end
    collection do
      patch :mark_all_as_read
    end
  end

  authenticated :user, ->(u) { u.admin? } do
    root 'static#admin', as: :admin_root
  end
  unauthenticated do
    root 'static#issue', as: :unauthenticated_root
  end
  root 'static#dashboard'
  get "sir" => "violations#sir"
  get 'my_citations' => 'citations#my_citations'
  get 'all_citations' => 'citations#all_citations'
  get 'admin_user' => 'static#admin_user'
  put "/update_user/:id", to: "static#update_user", as: "update_user"

  namespace :api do
    namespace :v1 do
      resources :addresses do
        member do
          get 'photos'
          get 'violations'
          get 'inspections'
          get 'complaints'
          get 'comments'
        end
      end
      resources :businesses
      resources :complaints
      resources :inspections
      resources :violations
      resources :codes
      resources :contacts
    end
  end
  mount ServiceWorker::Engine => "/service-worker.js"
end

app/models/unit.rb
class Unit < ApplicationRecord
  after_initialize :set_default_vacancy_status, if: :new_record?
  
  belongs_to :address
  has_many :violations
  has_many :comments
  has_many :citations
  has_many :inspections
  has_many :businesses
  has_many :unit_contacts
  has_many :contacts, through: :unit_contacts
  has_many :areas

  has_paper_trail

  # make sure that the unit number is unique for the address
  validates :number, uniqueness: { scope: :address_id }

  def to_s
    if vacancy_status == "vacant"
      "#{number} (vacant)"
    else
      number
    end
  end

  private

  def set_default_vacancy_status
    self.vacancy_status ||= "occupied"
  end
end

app/controllers/api/v1/businesses_controller.rb
class Api::V1::BusinessesController < ActionController::Base
  def index
    @businesses = Business.all
    render json: @businesses.map { |business| business.attributes.merge(address: business.address) }
  end

  def show
    @business = Business.find(params[:id])
    render json: @business
  end

  def create
    # Your code for creating a new business goes here
  end

  def update
    # Your code for updating an existing business goes here
  end

  def destroy
    # Your code for deleting a business goes here
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  layout 'choices', only: [:new, :edit, :new_business]
  before_action :authenticate_user!

  def index
    @business_q = Business.ransack(params[:q])
    @businesses = @business_q.result(distinct: true).order(created_at: :desc)

    case params[:licensed]
    when '1'
      @businesses = @businesses.joins(:licenses).where('licenses.expiration_date > ?', Date.today).distinct
    when '0'
      @businesses = @businesses.left_outer_joins(:licenses).where('licenses.expiration_date <= ? OR licenses.expiration_date IS NULL', Date.today).distinct
    end

    @businesses = @businesses.paginate(page: params[:page], per_page: 10)
  end

  def show
    @business = Business.find(params[:id])
    @address = @business.address
  end

  def new
    @address = Address.find(params[:address_id])
    @business = Business.new
  end

  def new_business
    @business = Business.new
  end

  def create_business
    @business = Business.new(business_params)
    address = Address.find(params[:business][:address_id])

    # Check if a new unit number is provided
    if @business.new_unit_number.present?
      # Create a new unit associated with the address
      unit = address.units.create(number: @business.new_unit_number)

      if unit.persisted?
        @business.unit = unit  # Associate the new unit with the business
      else
        Rails.logger.error "Failed to create unit: #{unit.errors.full_messages.join(', ')}"
        flash[:error] = 'Failed to create the new unit. Please try again.'
        render :new_business and return
      end
    end

    if @business.save
      flash[:success] = 'Business was successfully created.'
      redirect_to businesses_path # Adjust the redirection path if needed
    else
      Rails.logger.error "Failed to save business: #{@business.errors.full_messages.join(', ')}"
      render :new_business
    end
  end

  def new_unit_business
    @unit = Unit.find(params[:unit_id])
    @business = Business.new
  end

  def create
    @address = Address.find(params[:address_id])
    @business = @address.businesses.build(business_params)
  
    if @business.save
      flash[:success] = 'Business was successfully created.'
      redirect_to @address # You may want to adjust the redirection path
    else
      render :new
    end
  end
  

  def edit
    @address = Address.find(params[:address_id])
    @business = Business.find(params[:id])
  end

  def update
    @address = Address.find(params[:address_id])
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to address_business_path(@address, @business)
    else
      render 'edit'
    end
  end

  def destroy
    @address = Address.find(params[:address_id])
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to address_path(@address)
  end

  private

  def business_params
    params.require(:business).permit(:name, :phone, :email, :website, :address_id, :unit_id, :contact_ids, :trading_as, :new_unit_number)
  end
end

app/views/businesses/edit.html.erb
<h2>Edit Business</h2>

<%= form_for [@address, @business] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :trading_as %>
    <%= f.text_field :trading_as, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= f.label :contact_id %>
    <%= f.collection_select(:contact_ids, Contact.all, :id, :full_name_and_email, { prompt: 'Select or create a contact' }, class: 'form-control selectpicker', data: { style: 'btn-primary' }) %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.collection_select(:address_id, Address.all, :id, :property_name_with_combadd, { prompt: 'Select an address' }, { id: 'business_address_id', class: 'form-control selectpicker', data: { style: 'btn-primary' } }) %>
  </div>

  <!-- If the business has an address which contains units, display the units -->
  <% if @business.address.units.present? %>
    <div class="form-group">
      <%= f.label :unit_id %>
      <%= f.collection_select(:unit_id, @business.address.units, :id, :number, { prompt: 'Select a unit' }, class: 'form-control selectpicker', data: { style: 'btn-primary' }) %>
    </div>
  <% end %>

  <%= f.submit "Update Business", class: "btn btn-primary mt-3" %>
<% end %>

<script>
  // Function to initialize Choices.js
  function initializeChoices() {
    const contactSelect = new Choices('#business_contact_ids', {
      removeItemButton: true,
      searchEnabled: true,
      placeholder: true,
      placeholderValue: 'Select a contact',
    });

    const addressSelect = new Choices('#business_address_id', {
      removeItemButton: true,
      searchEnabled: true,
      placeholder: true,
      placeholderValue: 'Select an address',
    });
  }

  // Initialize Choices.js on page load
  document.addEventListener("turbo:load", initializeChoices);
</script>

app/views/businesses/index.html.erb
  <div class="card" style="background-color: #e3f2fd;">
    <div class="card-body">
      <%= search_form_for @business_q, url: businesses_path, method: :get do |f| %>
        <%= f.search_field :name_cont, class:"form-control form-control-lg", placeholder: "Search businesses" %>

        <div class="form-group mt-3 mb-3">
          <%= label_tag :licensed, 'Filter by license status' %>
          <%= select_tag :licensed, options_for_select([['All', ''], ['Licensed', '1'], ['Not Licensed', '0']], params[:licensed]), class: "form-control" %>
        </div>

        <div style="text-align:center"><%= f.submit "Search", class:"btn btn-primary" %></div>
      <% end %>
    </div>
  </div>
  
  <br>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body text-center">
        <h2>Businesses</h2>
        <%= link_to "New Business", new_business_path, class: "btn btn-outline-secondary", data: { turbo: false } %>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <% if @business_q.result.count == 0 %>
          <p>No businesses found.</p>
        <% else %>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Website</th>
                <th>Licensed?</th>
              </tr>
            </thead>
            <tbody>
              <% @businesses.each do |business| %>
                <tr>
                  <td><%= link_to business.business_name_and_trading_name, address_business_path(business.address, business), class: "btn btn-outline-secondary" %></td>
                  <td><%= link_to business.address.property_name_with_combadd, business.address, class: "btn btn-outline-secondary" %></td>
                  <td>
                    <% if business.phone.present? %>
                      <a href="tel:<%= business.phone %>"><%= format_phone_number(business.phone) %></a>
                    <% end %>
                  </td>
                  <td>
                    <% if business.email.present? %>
                      <%= link_to business.email, "mailto:#{business.email}" %>
                    <% end %>
                  </td>
                  <td>
                    <% if business.website.present? && business.website != "http://" %>
                        <a href="<%= business.website %>" target="_blank"><%= business.website %></a>
                    <% end %>
                  </td>
                  <td>
                    <span style="color: <%= business.licensed ? (business.licenses.last.sent? ? 'green' : 'red') : 'red' %>;">
                      <%= business.licensed ? (business.licenses.last.sent? ? 'Yes' : 'Yes (not sent)') : 'No' %>
                    </span>
                </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="text-center">
            <%= will_paginate @businesses, class: "pagination justify-content-center" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/businesses/new.html.erb
<h2>New Business</h2>
<%= form_for [@address, @business] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= f.label :contact_id %>
    <%= f.collection_select(:contact_ids, Contact.all, :id, :full_name_and_email, { prompt: 'Select or create a contact' }, class: 'form-control selectpicker', data: { style: 'btn-primary' }) %>
  </div>
  
  <%= f.submit "Create Business", class: "btn btn-primary mt-3" %>
<% end %>

<script>
  // Function to initialize Choices.js
  function initializeChoices() {
    const contactSelect = new Choices('#business_contact_ids', {
      removeItemButton: true,
      searchEnabled: true,
      placeholder: true,
      placeholderValue: 'Select a contact',
    });
  }

  // Initialize Choices.js on page load
  document.addEventListener("turbo:load", initializeChoices);
</script>

app/views/businesses/new_business.html.erb
<h2>New Business</h2>
<%= form_for @business, url: new_business_path, method: :post do |f| %>
  <div class="form-group">
    <label>Address</label>
    <%= f.collection_select(:address_id, Address.all, :id, :combadd, { prompt: 'Select an address' }, class: 'form-control selectpicker', data: { style: 'btn-primary' }) %>
  </div>

  <div class="form-group" id="units-group" style="display: none;">
    <label>Units</label>
    <%= f.collection_select(:unit_id, [], :id, :number, { prompt: 'Select a unit' }, class: 'form-control selectpicker', id: 'business_unit_id') %>
    <option value="">No Unit</option> <!-- Add this line -->
    <label>Or Enter New Unit Number</label>
    <%= f.text_field :new_unit_number, class: 'form-control', id: 'new_unit_number', placeholder: 'Enter new unit number' %>
  </div>


  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Trading As</label>
    <%= f.text_field :trading_as, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= f.label :contact_id %>
    <%= f.collection_select(:contact_ids, Contact.all, :id, :full_name_and_email, { prompt: 'Select a contact' }, class: 'form-control selectpicker', data: { style: 'btn-primary' }) %>
  </div>
  
  <%= f.submit "Create Business", class: "btn btn-primary mt-3" %>
<% end %>

<script>
  document.addEventListener("turbo:load", function () {
    initializeChoices();

    // Address change event
    document.querySelector('#business_address_id').addEventListener('change', function (event) {
      const addressId = event.target.value;

      // Fetch units for the selected address
      if (addressId) {
        fetchUnitsForAddress(addressId);
      } else {
        hideUnitsDropdown();
      }
    });

    // Event listener to toggle manual unit number entry
    document.querySelector('#business_unit_id').addEventListener('change', function (event) {
      const selectedUnit = event.target.value;
      toggleNewUnitField(selectedUnit);
    });
  });

  function initializeChoices() {
    new Choices('#business_contact_ids', {
      removeItemButton: true,
      searchEnabled: true,
      placeholder: true,
      placeholderValue: 'Select a contact',
    });

    new Choices('#business_address_id', {
      removeItemButton: true,
      searchEnabled: true,
      placeholder: true,
      placeholderValue: 'Select an address',
    });
  }

  function fetchUnitsForAddress(addressId) {
    fetch(`/addresses/${addressId}/units`)
      .then(response => response.json())
      .then(data => {
        const unitsSelect = document.querySelector('#business_unit_id');
        unitsSelect.innerHTML = ''; // Clear existing options

        // Add "No Unit" option
        const noUnitOption = document.createElement('option');
        noUnitOption.value = '';
        noUnitOption.text = 'No Unit';
        unitsSelect.appendChild(noUnitOption);

        if (data.units && data.units.length > 0) {
          data.units.forEach(unit => {
            const option = document.createElement('option');
            option.value = unit.id;
            option.text = unit.number; // Use `number` to display the unit number
            unitsSelect.appendChild(option);
          });

          showUnitsDropdown();
          toggleNewUnitField(unitsSelect.value); // Hide new unit field if units are available
        } else {
          showUnitsDropdown();
          toggleNewUnitField(null); // Show new unit field if no units are available
        }
      })
      .catch(error => console.error('Error fetching units:', error));
  }

  function showUnitsDropdown() {
    document.querySelector('#units-group').style.display = 'block';
  }

  function hideUnitsDropdown() {
    document.querySelector('#units-group').style.display = 'none';
    document.querySelector('#business_unit_id').innerHTML = '';
  }

  // Function to show or hide the new unit number field
  function toggleNewUnitField(selectedUnit) {
    const newUnitField = document.querySelector('#new_unit_number');
    if (selectedUnit && selectedUnit !== '') {
      newUnitField.style.display = 'none'; // Hide the new unit field if an existing unit is selected
    } else {
      newUnitField.style.display = 'block'; // Show the new unit field if no unit is selected or no units are available
    }
  }

</script>

app/views/businesses/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">
      <%= link_to "Home", root_path %>
    </a></li>
    <li class="breadcrumb-item"><a href="#">
    <%= link_to @address.property_name_with_combadd, address_path(@address) %>
    </a></li>
    <li class="breadcrumb-item active" aria-current="page">
      <%= @business.business_name_and_trading_name %>
    </li>
  </ol>
</nav>
<div class="card">
  <div class="card-body">
    <h2>  
      <%= @business.business_name_and_trading_name %>
    </h2>

    <p>
      <strong><label>Phone:</label></strong>
                <% if @business.phone.present? %>
                  <a href="tel:<%= @business.phone %>"><%= format_phone_number(@business.phone) %></a>
                <% end %>
    </p>
    <p>
      <strong><label>Email:</label></strong>
                <% if @business.email.present? %>
                  <%= link_to @business.email, "mailto:#{@business.email}" %>
                <% end %></p>
    <p>
      <strong><label>Website:</label></strong>
                <% if @business.website.present? %>
                    <a href="<%= @business.website %>" target="_blank"><%= @business.website %></a>
                <% end %></p>

    <p>
      <strong><label>Contact:</label></strong>
                <% if @business.contacts.any? %>
                  <% @business.contacts.each do |contact| %>
                    <%= link_to contact.full_name_and_email, contact_path(contact) %><br>
                  <% end %>
                <% end %>
    </p>

    <p>
      <strong><label>Address:</label></strong>
                <%= link_to @business.address.property_name_with_combadd, address_path(@business.address) %>
    </p>

    <!-- if the business has a unit, display the unit -->
    <% if @business.unit.present? %>
      <p>
        <strong><label>Unit:</label></strong>
        <%= link_to @business.unit.number, address_unit_path(@business.address, @business.unit) %>
      </p>
    <% end %>
    
    <%= link_to "Edit", edit_address_business_path(@business.address, @business), class: "btn btn-outline-secondary", data: { turbo: false } %>

    <br>
    <br>
    <h3>License inspection</h3>
    <% if @business.contacts.present? %>
      <%= link_to "Request an inspection", new_address_inspection_path(@address, source: 'Business license', description: @business.business_name_and_trading_name, contact_ids: @business.contacts.first.id, business_id: @business.id), class: "btn btn-outline-primary", data: { turbo: false } %>
    <% else %>
      <%= link_to "Request an inspection", new_address_inspection_path(@address, source: 'Business license', description: @business.business_name_and_trading_name, business_id: @business.id), class: "btn btn-outline-primary", data: { turbo: false } %>
    <% end %>
    <br>
    <div class="mt-3">
      <h3>Business Violations 
      <% if @business.violations.any? %>
        (<%= @business.violations.count %>)
      <% end %>
      </h3>
      <div class="mt-3">
        <%= link_to 'Add Violation', new_business_violation_path(@business), class: "btn btn-outline-danger" %>
      </div>
      <% if @business.violations.any? %>
      <div class="table-responsive-sm">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Violation Type</th>
              <th>Deadline</th>
              <th>Codes</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @business.violations.each do |violation| %>
              <tr>
                <td><%= violation.violation_type %></td>
                <td><%= violation.deadline %></td>
                <td>
                  <% violation.codes.each do |code| %>
                    <%= render partial: 'shared/code_def_show', locals: { code: code } %>
                  <% end %>
                </td>
                <td><%= link_to "View", violation_path(violation) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
    <!-- table of inspections for this business -->
    <% if @business.inspections.any? %>
    <br>
      <h3>
      Inspections
      <% if @business.inspections.any? %>
        (<%= @business.inspections.count %>)
      <% end %>
      </h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Source</th>
            <th>Scheduled</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @business.inspections.each do |inspection| %>
            <tr>
              <td><%= inspection.source %></td>
              <% if inspection.scheduled_datetime.present? %>
                <td><%= inspection.scheduled_datetime.strftime("%m/%d/%Y %I:%M %p") %></td>
              <% else %>
                <td>Not scheduled</td>
              <% end %>
              <% if inspection.status == nil %>
                <td>Pending</td>
              <% else %>
              <td><%= inspection.status %></td>
              <% end %>
              <td><%= link_to "View", address_inspection_path(inspection.address, inspection) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <% if @business.licenses.any? %>
  <br>
  <h3>
    Licenses
    (<%= @business.licenses.count %>)
  </h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Fiscal Year</th>
        <th>Expiration Date</th>
        <th>Sent?</th>
      </tr>
    </thead>
    <tbody>
      <% @business.licenses.each do |license| %>
        <tr>
          <td><%= link_to license.fiscal_year, license_path(license) %></td>
          <td><%= license.expiration_date.strftime("%m/%d/%Y") %></td>
          <td>
            <% if license.sent == true %>
              <p class="text-success">Yes</p>
            <% else %>
              <p class="text-danger">No</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
  </div>
</div>