config/routes.rb
Rails.application.routes.draw do
  resources :codes
  resources :rooms do
    resources :prompts
  end
  resources :contacts do
    resources :contact_comments
    member do
      get 'add_notes'
      patch :hide
    end
  end
  devise_for :users
  resources :addresses do
    resources :violations, shallow: true do
      resources :citations, shallow: true do
        resources :citation_comments
      end
      member do
        get :extend_deadline
        patch :update_deadline
        get :units
      end
      patch :resolve, on: :member
      patch :update, on: :member
      get :generate_report, on: :member
      resources :violation_comments
      collection do
        get :export_csv
      end
    end
    resources :comments
    resources :concerns, only: [:create, :edit, :update]
    resources :units, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      member do
        get 'new_unit_business', to: 'businesses#new_unit_business'
        get 'all_unit_comments'
        get 'all_unit_violations'
        get 'all_unit_citations'
        get 'all_unit_inspections'
        get 'all_unit_complaints'
        get 'manage_contacts'
        post 'manage_contacts'
        delete 'remove_contact'
        get :set_potentially_vacant
        get :set_vacant
        get :set_occupied
      end
    end
    resources :inspections do
      member do
        get 'conduct'
        get 'schedule'
        post 'save_and_redirect_to_area_new'
        get 'create_business_license'
        get 'create_single_family_license'
        get 'create_multifamily_license'
        get 'create_permit'
      end
      resources :areas do
        resources :observations, only: [:create, :edit, :update]
      end
      resources :inspection_comments
      resources :licenses, except: [:index]
    end
    resources :businesses, except: [:index, :new_business]
    member do
      get 'manage_contacts'
      post 'manage_contacts'
      delete 'remove_contact'
      get 'address_name'
      get 'all_address_violations'
      get 'all_address_comments'
      get 'all_address_citations'
      get 'all_address_inspections'
      get 'all_address_complaints'
      get 'add_aka'
      get :set_potentially_vacant
      get :set_vacant
      get :set_occupied
      get :set_registered
    end
    collection do
      get :potentially_vacant
      get :vacant
    end
  end

  resources :licenses do
    get 'email_license' => 'licenses#email_license'
    get 'download_license' => 'licenses#download_license'
    member do
      put 'sent_today' => 'licenses#sent_today' 
      put 'not_sent' => 'licenses#not_sent'
      put 'paid' => 'licenses#paid'
      put 'not_paid' => 'licenses#not_paid'
      get 'generate_business'
      get 'generate_single_family'
    end
  end

  resources :permits do
    member do
      put 'sent' => 'permits#sent'
      put 'revoked' => 'permits#revoked'
      put 'paid' => 'permits#paid'
    end
  end

  get 'all_inspections' => 'inspections#all_inspections'
  get 'my_inspections' => 'inspections#my_inspections'
  get 'my_unscheduled_inspections' => 'inspections#my_unscheduled_inspections'
  get 'all_complaints' => 'inspections#all_complaints'
  get 'my_complaints' => 'inspections#my_complaints'
  get 'all_violations' => 'violations#violist'
  get 'my_violations' => 'addresses#my_violations'
  get 'helpful' => 'static#helpful'
  get 'businesses' => 'businesses#index'
  patch 'mark_reviewed/:id' => 'static#mark_reviewed', as: 'mark_reviewed'
  get 'design_test' => 'static#design_test'
  get 'new_business' => 'businesses#new_business'
  post 'new_business' => 'businesses#create_business'
  get 'new_complaint' => 'inspections#new_complaint'
  post 'new_complaint' => 'inspections#create_complaint'
  get 'new_permit_inspection' => 'inspections#new_permit_inspection'
  post 'new_permit_inspection' => 'inspections#create_permit_inspection'
  get 'new_license_inspection' => 'inspections#new_license_inspection'
  post 'new_license_inspection' => 'inspections#create_license_inspection'
  get 'unassigned_inspections' => 'inspections#unassigned_inspections'
  get 'assign_inspection/:id' => 'inspections#assign_inspection', as: 'assign_inspection'
  patch 'update_inspector/:id' => 'inspections#update_inspector', as: 'update_inspector'
  get 'inspection_calendar' => 'inspections#inspection_calendar'
  get 'new_business_violation/:business_id' => 'violations#new_business_violation', as: 'new_business_violation'
  get 'all_licenses' => 'licenses#index'
  get 'all_permits' => 'permits#index'
  get 'map' => 'static#map'
  get 'export_violations' => 'violations#export_csv'
  get 'export_property_csv' => 'violations#export_property_csv'
  patch 'inspections/:id/mark_as_paid', to: 'inspections#mark_as_paid', as: :mark_as_paid
  patch 'inspections/:id/mark_as_not_paid', to: 'inspections#mark_as_not_paid', as: :mark_as_not_paid
  post 'create_unit' => 'inspections#create_unit'

  resources :users, only: [:index, :show, :edit, :update]
  resources :notifications do
    member do
      patch :mark_as_read
    end
    collection do
      patch :mark_all_as_read
    end
  end

  authenticated :user, ->(u) { u.admin? } do
    root 'static#admin', as: :admin_root
  end
  unauthenticated do
    root 'static#issue', as: :unauthenticated_root
  end
  root 'static#dashboard'
  get "sir" => "violations#sir"
  get 'my_citations' => 'citations#my_citations'
  get 'all_citations' => 'citations#all_citations'
  get 'admin_user' => 'static#admin_user'
  put "/update_user/:id", to: "static#update_user", as: "update_user"

  namespace :api do
    namespace :v1 do
      resources :addresses do
        member do
          get 'photos'
          get 'violations'
          get 'inspections'
          get 'complaints'
          get 'comments'
        end
      end
      resources :businesses
      resources :complaints
      resources :inspections
      resources :violations
      resources :codes
      resources :contacts
    end
  end
  mount ServiceWorker::Engine => "/service-worker.js"
end

app/views/shared/_dash.html.erb
<% if current_user.ons? || current_user.admin? %>
<div class="row">
  <div class="col-lg-12">
    <!-- Today's inspections card -->
    <% if @today_inspections.empty? %>
      <div class="card flex-fill w-100 d-none d-lg-block">
    <% else %>
      <div class="card flex-fill w-100">
    <% end %>
      <div class="card-header">
        <h5 class="card-title mb-0">Today's inspections</h5>
      </div>
      <div class="card-body py-3">
        <% if @today_inspections.empty? %>
          <p>No inspections scheduled for today.</p>
          <%= link_to "Inspections this week", inspection_calendar_path, class: "btn btn-outline-primary" %>
        <% else %>
          <table class="table">
            <thead>
              <tr>
                <th>Property</th>
                <th>Scheduled Time</th>
              </tr>
            </thead>
            <tbody>
              <% @today_inspections.each do |inspection| %>
                <tr>
                  <td><%= link_to inspection.address.property_name_with_combadd, address_inspection_path(inspection.address, inspection) %></td>
                  <td><%= inspection.scheduled_datetime.strftime("%I:%M %p") %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>

    <!-- Weekly progress card -->
    <div class="card flex-fill w-100">
      <div class="card-header">
        <h5 class="card-title mb-0">Weekly Progress</h5>
      </div>
      <div class="card-body py-3">
        <div class="row">
          <div class="col">
            <h2 class="mb-1"><%= "This week: " + @weekly_inspections.count.to_s + " Inspections" %></h2>
            <div class="d-flex align-items-center">
              <div class="text-success">
                <i class="mdi mdi-arrow-up-bold"></i>
              </div>
              <div class="<%= @last_week_inspections.count < @weekly_inspections.count ? 'text-success' : @last_week_inspections.count == @weekly_inspections.count ? '' : 'text-danger' %> ms-2">
                <%= "Last week: " + (@last_week_inspections.count).to_s %>
              </div>
            </div>
          </div>
    
          <div class="col">
            <h2 class="mb-1"><%= "This week: " + @weekly_violations.count.to_s + " Violation Notices/Doorhangers" %></h2>
            <div class="d-flex align-items-center">
              <div class="text-danger">
                <i class="mdi mdi-arrow-down-bold"></i>
              </div>
              <div class="<%= @last_week_violations.count < @weekly_violations.count ? 'text-success' : @last_week_violations.count == @weekly_violations.count ? '' : 'text-danger' %> ms-2">
                <%= "Last week: " + (@last_week_violations.count).to_s %>
              </div>
            </div>
          </div>
    
          <!-- New Comments Section -->
          <div class="col">
            <h2 class="mb-1"><%= "This week: " + @weekly_comments.count.to_s + " Comments" %></h2>
            <div class="d-flex align-items-center">
              <div class="text-primary">
                <i class="mdi mdi-comment"></i>
              </div>
              <div class="<%= @last_week_comments.count < @weekly_comments.count ? 'text-success' : @last_week_comments.count == @weekly_comments.count ? '' : 'text-danger' %> ms-2">
                <%= "Last week: " + (@last_week_comments.count).to_s %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    


<div class="d-flex justify-content-center">
  <ul class="nav nav-pills nav-justified mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="pills-inspections-tab" data-bs-toggle="pill" data-bs-target="#pills-inspections" type="button" role="tab" aria-controls="pills-inspections" aria-selected="true" style="font-size: larger;">Inspections (<%= @inspections.count %>)</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-violations-tab" data-bs-toggle="pill" data-bs-target="#pills-violations" type="button" role="tab" aria-controls="pills-violations" aria-selected="false" style="font-size: larger;">Violations (<%= @violations.count %>)</button>
    </li>
  </ul>
</div>
</div>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-inspections" role="tabpanel" aria-labelledby="pills-inspections-tab">
    <!-- show a table of @inspections -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Inspections (<%= @inspections.count %>)</h3>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table id="example1" class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">Address</th>
                <th scope="col">Type</th>
                <th scope="col">Paid?</th>
                <th scope="col">Status</th>
                <th scope="col">Scheduled Date</th>
                <th scope="col">Inspector</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% if @inspections_dash.nil? %>
                <% @inspections.each do |inspection| %>
                  <%= render partial: 'shared/inspection_table', locals: { inspection: inspection } %>
                <% end %>
              <% else %>
                <% @inspections_dash.each do |inspection| %>
                  <%= render partial: 'shared/inspection_table', locals: { inspection: inspection } %>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-violations" role="tabpanel" aria-labelledby="pills-violations-tab">
    <!-- show a table of @violations -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Violations with deadlines which have passed (<%= @violations.count %>)</h3>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table id="example2" class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">Address</th>
                <th scope="col">Created By</th>
                <th scope="col">Created At</th>
                <th scope="col">Violation Type</th>
                <th scope="col">Code</th>
                <th scope="col">Deadline Date</th>
                <th scope="col">Citations</th>
              </tr>
            </thead>
            <tbody>
              <% @violations.each do |violation| %>
                <%= render partial: 'shared/violation_table', locals: { violation: violation } %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


    
<!--
</div>
  <div class="col-lg-4">
    <% if @complaints.empty? %>
    <div class="card d-none d-lg-block shadow mb-3" onclick="window.location='<%= all_complaints_path(inspector: 'My Complaints') %>';" style="cursor: pointer;">
    <% else %>          
    <div class="card shadow mb-3" onclick="window.location='<%= all_complaints_path(inspector: 'My Complaints', status: 'Pending') %>';" style="cursor: pointer; background-color:#ffcccc">
    <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col mt-0">
            <h5 class="card-title">Active Property Complaints</h5>
          </div> 
          <div class="col-auto">
            <div class="stat text-primary">
              C
            </div>
          </div>
        </div>
        <h1 class="mt-1 mb-3">
          <%= @complaints.count %>
        </h1>
      </div>
    </div>
    <% if @active_violations.empty? %>
    <div class="card shadow mb-3 d-none d-lg-block" onclick="window.location='<%= all_violations_path(user: 'current_user_current') %>';" style="cursor: pointer;">
    <% else %>
    <div class="card shadow mb-3" onclick="window.location='<%= all_violations_path(user: 'current_user_current') %>';" style="cursor: pointer; background-color:#ffcccc">
    <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col mt-0">
            <h5 class="card-title">Violations Requiring Attention</h5>
          </div>
          <div class="col-auto">
            <div class="stat text-primary">
              V
            </div>
          </div>
        </div>
        <h1 class="mt-1 mb-3">
            <%= @violations.count %>
        </h1>
        <div class="mb-0">
          <span class=""> <i class="mdi mdi-arrow-bottom-right"></i>
            <%= @active_violations.count %>
          </span>
        <span class="text-muted">Total Active Violations</span>
        </div>
      </div>
    </div>

    <% if @unscheduled_inspections.present? %>
    <%# A different colored card for unscheduled inspections %>
    <div class="card d-none d-lg-block shadow mb-3" onclick="window.location='<%= all_inspections_path(inspector: 'My Unscheduled') %>';" style="cursor: pointer; background-color:#ffcccc">
      <div class="card-body">
        <div class="row">
          <div class="col mt-0">
            <h5 class="card-title">Inspections to be scheduled</h5>
          </div>
          <div class="col-auto">
            <div class="stat text-primary">
              I
            </div>
          </div>
        </div>
        <h1 class="mt-1 mb-3">
          <%= @unscheduled_inspections.count %>
        </h1>
      </div>
    </div>
    <% end %>
  </div>
</div>-->
<% end %>

<% if current_user.oas? %>
<div class="row">
  <div class="col">
    <div class="card">  
      <div class="card-body">
        <h5 class="card-title">Thank you for signing in!</h5>
        <p>I've added a few instructions below to help you get started. If you have any additional questions, feel free to give me a call.</p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
      <h5 class="card-title">Addresses</h5>
        <p>For information on a specific address, use the search bar above.</p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xl-6">
    <!-- informative cards -->
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Inspections/Complaints</h5>
        <p class="card-text">
          Complaints, inspections, and violations are all related to addresses.
        </p>
        <p class="card-text">
          If you are looking for a list of previously requested inspections, click the "Inspections" button below. If you are looking for a previously requested complaint, click the "Complaints" button below.
        </p>
        
        <div class="btn-group" role="group" aria-label="Inspections and Complaints">
          <%= link_to "Inspections", all_inspections_path, class: "btn btn-outline-secondary" %>
          <%= link_to "Complaints", all_complaints_path, class: "btn btn-outline-secondary" %>
          <%= link_to "New Complaint", new_complaint_path, class: "btn btn-outline-danger", data: { turbo: false } %>
          <%= link_to "New Permit", new_permit_inspection_path, class: "btn btn-outline-danger", data: { turbo: false } %>
          <%= link_to "New License", new_license_inspection_path, class: "btn btn-outline-danger", data: { turbo: false } %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Contacts</h5>
        <p class="card-text">
          To find a list of all contacts, or to add a new contact, click the "Contacts" button below.
        </p>
        <%= link_to "Contacts", contacts_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>
  <div class="col-xl-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Citations</h5>
        <p class="card-text">
          To find the list of all current citations, click the "Citations" button below. In order to update the citation from unpaid to paid, click on the "unpaid" button.
        </p>
        <%= link_to "Citations", all_citations_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>
  <div class="col-xl-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Businesses</h5>
        <p class="card-text">
          To find a list of all businesses, click the businesses button below. To add a new business, click the "Add New Business" button on an address page.
        </p>
        <div class="btn-group" role="group" aria-label="Businesses">
          <%= link_to "Businesses", businesses_path, class: "btn btn-outline-secondary" %>
          <%= link_to "Add New Business", new_business_path, class: "btn btn-outline-secondary", data: { turbo: false } %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_inspection_table3.html.erb
<%# table for inspections %>

<tr class="">
  <%# if show_address_info %>
  <!-- <td><%= link_to inspection.address.combadd.titleize, address_path(inspection.address), class:"btn btn-secondary" %></td> -->
  <%# end %>
  <td><%= inspection.created_at.strftime("%B %d, %Y %I:%M %p") %></td>
  <td><%= inspection.source %></td>
  <td><%= link_to inspection.address.property_name_with_combadd, address_inspection_path(inspection.address, inspection) %></td>
  <% if inspection.scheduled_datetime.present? %>
    <td><%= inspection.scheduled_datetime.strftime("%B %d, %Y %I:%M %p") %></td>
  <% else %>
    <td>
      <%= link_to "Schedule inspection", schedule_address_inspection_path(inspection.address, inspection), class: "btn btn-outline-primary" %>
    </td>
  <% end %>

  <td>
    <%= link_to "Assign", assign_inspection_path(inspection), class: "btn btn-outline-primary" %>
  </td>
</tr>

app/views/shared/_potentially_vacant_rows.html.erb
<% if item.is_a?(Address) %>
  <tr>
    <td><%= link_to item.property_name_with_combadd, address_path(item), class: 'btn btn-primary' %></td>
    <td><%= link_to 'Mark as Occupied', set_occupied_address_path(item), method: :get, class: 'btn btn-outline-secondary' %></td>
    <td><%= link_to 'Mark as Vacant', set_vacant_address_path(item), method: :get, class: 'btn btn-outline-secondary' %></td>
  </tr>
<% else %>
  <tr>
    <td><%= link_to "#{item.address.property_name_with_combadd} Unit #{item.number}", address_unit_path(item.address, item), class: 'btn btn-primary' %></td>
    <td><%= link_to 'Mark as Occupied', set_occupied_address_unit_path(item.address, item), method: :get, class: 'btn btn-outline-secondary' %></td>
    <td><%= link_to 'Mark as Vacant', set_vacant_address_unit_path(item.address, item), method: :get, class: 'btn btn-outline-secondary' %></td>
  </tr>
<% end %>

app/views/shared/_unit_info.html.erb
<div class="col-md-4 col-xl-3">
  <div class="card mb-3">
    <div class="card-header">
      <h5 class="card-title mb-0">Unit Details</h5>
    </div>
    <div class="card-body text-center">
      <h3 class="mb-0">
        <%= @address.property_name_with_combadd %>
      </h3>
      <h1>
        <%= @unit.number.upcase %>
      </h1>
      <div>
        <% if @address.property_name.present? %>
          <p><strong>Property Name:</strong> <%= @address.property_name.titleize %></p>
          <%= link_to "Edit Property Name", address_name_address_path(@address), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
        <% else %>
          <%= link_to "Add property name", address_name_address_path(@address), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
        <% end %>
        <a class="btn btn-outline-secondary btn-sm mt-2" href="https://www.google.com/maps/search/?api=1&query=<%= @address.combadd %>+MD+<%= @address.premisezip %>" target="_blank">Google Map</a>
      </div>
    </div>
    <!-- only shows up when screen is small -->
    <div class="d-block d-md-none">
      <!-- Button to show collapsed div -->
      <div class="card-body text-center">
        <button class="btn btn-outline-primary btn-sm mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#mobileCollapse" aria-expanded="false" aria-controls="mobileCollapse">
          Show More
        </button>
      </div>    
      <div id="mobileCollapse" class="collapse">
        <!-- Owner info -->
        <hr class="my-0">
        <div class="card-body">
          <h5 class="h6 card-title">Property Owner Information</h5>
          <p><strong>Owner Name:</strong> <%= @address.ownername.titleize %></p>
          <p><strong>Owner Address:</strong><%= @address.owneraddress %> <%= @address.ownercity %>, <%= @address.ownerstate %> <%= @address.ownerzip %></p>
          <div class="text-center">
            <%= link_to "Update Owner Info", edit_address_path(@address), class: "btn btn-outline-secondary btn-sm mt-2" %>
          </div>
        </div>
        <!-- contacts -->
        <hr class="my-0">
        <div class="card-body">
          <h5 class="h6 card-title">Contacts Associated With <%= @unit.number.upcase %></h5>
          <% if @unit.contacts.present? %>
            <% @unit.contacts.each do |c| %>
              <%= link_to c.name, contact_path(c), class: "btn btn-outline-info btn-sm mt-2" %>
            <% end %>
          <% end %>
          <div class="text-center">
            <% if @unit.contacts.present? %>
              <%= link_to "Manage Contacts", manage_contacts_address_unit_path(@unit.address, @unit), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
            <% else %>
              <%= link_to "Add Contact", manage_contacts_address_unit_path(@unit.address, @unit), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
            <% end %>
          </div>
        </div>
        <!-- units -->
        <hr class="my-0">
        <div class="card-body">
          <h5 class="h6 card-title">All Property Units</h5>
          <div class="">
            <% for unit in @address.units %>
              <%= link_to unit.number, address_unit_path(@address, unit), class: "btn btn-outline-info btn-sm mt-2" %>
            <% end %>
            <div class="text-center">
              <%= link_to "Add Units", new_address_unit_path(@address), class: "btn btn-outline-secondary btn-sm mt-2" %>
            </div>
          </div>
        </div>
        <!-- businesses -->
        <hr class="my-0">
        <div class="card-body">
          <h5 class="h6 card-title">Business</h5>
            <% if @address.businesses.present? %>
              <% @address.businesses.each do |b| %>
                <%= link_to b.name, address_business_path(b.address, b), class: "btn btn-outline-info btn-sm mt-2" %>
              <% end %>
            <% end %>
          <div class="text-center">
            <%= link_to "Add Business", new_address_business_path(@address), class: "btn btn-outline-primary btn-sm mt-2", data: { turbo: false } %>
          </div>
        </div>
        <!-- violations -->
        <hr class="my-0">
        <div class="card-body">
          <h5 class="h6 card-title">Property Violation</h5>
          <div class="text-center">
            <%= link_to "Create a Violation Notice/Doorhanger", new_address_violation_path(@address), class: "btn btn-danger btn-sm mt-2", data: { turbo: false } %>
          </div>
        </div>
        <!-- inspections -->
        <hr class="my-0">
        <div class="card-body">
          <h5 class="h6 card-title">New Complaint or Inspection Request</h5>
          <div class="text-center">
            <%= link_to "Create New Inspection Request", new_address_inspection_path(@address), class: "btn btn-info btn-sm mt-2", data: { turbo: false } %>
          </div>
        </div>
      </div>
    </div>
    <!-- only shows up when screen is medium or larger -->
    <div class="d-none d-md-block">
      <!-- Owner info -->
      <hr class="my-0">
      <div class="card-body">
        <h5 class="h6 card-title">Property Owner Information</h5>
        <p><strong>Owner Name:</strong> <%= @address.ownername.titleize %></p>
        <p><strong>Owner Address:</strong><%= @address.owneraddress %> <%= @address.ownercity %>, <%= @address.ownerstate %> <%= @address.ownerzip %></p>
        <div class="text-center">
          <%= link_to "Update Owner Info", edit_address_path(@address), class: "btn btn-outline-secondary btn-sm mt-2" %>
        </div>
      </div>
      <!-- contacts -->
      <hr class="my-0">
      <div class="card-body">
        <h5 class="h6 card-title">Contacts Associated With <%= @unit.number.upcase %></h5>
        <% if @unit.contacts.present? %>
          <% @unit.contacts.each do |c| %>
            <%= link_to c.name, contact_path(c), class: "btn btn-outline-info btn-sm mt-2" %>
          <% end %>
        <% end %>
        <div class="text-center">
          <% if @unit.contacts.present? %>
            <%= link_to "Manage Contacts", manage_contacts_address_unit_path(@unit.address, @unit), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
          <% else %>
            <%= link_to "Add Contact", manage_contacts_address_unit_path(@unit.address, @unit), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
          <% end %>
        </div>
      </div>
      <!-- units -->
      <hr class="my-0">
      <div class="card-body">
        <h5 class="h6 card-title">All Property Units</h5>
        <div class="">
          <% for unit in @address.units %>
            <%= link_to unit.number, address_unit_path(@address, unit), class: "btn btn-outline-info btn-sm mt-2" %>
          <% end %>
          <div class="text-center">
            <%= link_to "Add Units", new_address_unit_path(@address), class: "btn btn-outline-secondary btn-sm mt-2" %>
          </div>
        </div>
      </div>
      <!-- businesses -->
      <hr class="my-0">
      <div class="card-body">
        <h5 class="h6 card-title">All Property Businesses</h5>
          <% if @address.businesses.present? %>
            <% @address.businesses.each do |b| %>
              <%= link_to b.name, address_business_path(b.address, b), class: "btn btn-outline-info btn-sm mt-2" %>
            <% end %>
          <% end %>
        <div class="text-center">
          <%= link_to "Add Business", new_address_business_path(@address), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
        </div>
        <br>
        <h5 class="h6 card-title">Unit Business(es)</h5>
          <% if @unit.businesses.present? %>
            <% @unit.businesses.each do |b| %>
              <%= link_to b.name, business_path(b), class: "btn btn-outline-info btn-sm mt-2" %>
            <% end %>
          <% end %>
        <div class="text-center">
          <%= link_to "Add Business", new_unit_business_address_unit_path(@address, @unit), class: "btn btn-outline-secondary btn-sm mt-2", data: { turbo: false } %>
        </div>
      </div>
      <!-- violations -->
      <hr class="my-0">
      <div class="card-body">
        <h5 class="h6 card-title">Property Violation</h5>
        <div class="text-center">
          <%= link_to "Create a Violation Notice/Doorhanger", new_address_violation_path(@address), class: "btn btn-danger btn-sm mt-2", data: { turbo: false } %>
        </div>
      </div>
      <!-- inspections -->
      <hr class="my-0">
      <div class="card-body">
        <h5 class="h6 card-title">New Complaint or Inspection Request</h5>
        <div class="text-center">
          <%= link_to "Create New Inspection Request", new_address_inspection_path(@address), class: "btn btn-info btn-sm mt-2", data: { turbo: false } %>
        </div>
      </div>
    </div>
  </div>
</div>