config/routes.rb
Rails.application.routes.draw do
  resources :codes
  resources :rooms do
    resources :prompts
  end
  resources :contacts do
    resources :contact_comments
    member do
      get 'add_notes'
      patch :hide
    end
  end
  devise_for :users
  resources :addresses do
    resources :violations, shallow: true do
      resources :citations, shallow: true do
        resources :citation_comments
      end
      member do
        get :extend_deadline
        patch :update_deadline
        get :units
      end
      patch :resolve, on: :member
      patch :update, on: :member
      get :generate_report, on: :member
      resources :violation_comments
      collection do
        get :export_csv
      end
    end
    resources :comments
    resources :concerns, only: [:create, :edit, :update]
    resources :units, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      member do
        get 'new_unit_business', to: 'businesses#new_unit_business'
        get 'all_unit_comments'
        get 'all_unit_violations'
        get 'all_unit_citations'
        get 'all_unit_inspections'
        get 'all_unit_complaints'
        get 'manage_contacts'
        post 'manage_contacts'
        delete 'remove_contact'
        get :set_potentially_vacant
        get :set_vacant
        get :set_occupied
      end
    end
    resources :inspections do
      member do
        get 'conduct'
        get 'schedule'
        post 'save_and_redirect_to_area_new'
        get 'create_business_license'
        get 'create_single_family_license'
        get 'create_multifamily_license'
        get 'create_permit'
      end
      resources :areas do
        resources :observations, only: [:create, :edit, :update]
      end
      resources :inspection_comments
      resources :licenses, except: [:index]
    end
    resources :businesses, except: [:index, :new_business]
    member do
      get 'manage_contacts'
      post 'manage_contacts'
      delete 'remove_contact'
      get 'address_name'
      get 'all_address_violations'
      get 'all_address_comments'
      get 'all_address_citations'
      get 'all_address_inspections'
      get 'all_address_complaints'
      get 'add_aka'
      get :set_potentially_vacant
      get :set_vacant
      get :set_occupied
      get :set_registered
    end
    collection do
      get :potentially_vacant
      get :vacant
    end
  end

  resources :licenses do
    get 'email_license' => 'licenses#email_license'
    get 'download_license' => 'licenses#download_license'
    member do
      put 'sent_today' => 'licenses#sent_today' 
      put 'not_sent' => 'licenses#not_sent'
      put 'paid' => 'licenses#paid'
      put 'not_paid' => 'licenses#not_paid'
      get 'generate_business'
      get 'generate_single_family'
    end
  end

  resources :permits do
    member do
      put 'sent' => 'permits#sent'
      put 'revoked' => 'permits#revoked'
      put 'paid' => 'permits#paid'
    end
  end

  get 'all_inspections' => 'inspections#all_inspections'
  get 'my_inspections' => 'inspections#my_inspections'
  get 'my_unscheduled_inspections' => 'inspections#my_unscheduled_inspections'
  get 'all_complaints' => 'inspections#all_complaints'
  get 'my_complaints' => 'inspections#my_complaints'
  get 'all_violations' => 'violations#violist'
  get 'my_violations' => 'addresses#my_violations'
  get 'helpful' => 'static#helpful'
  get 'businesses' => 'businesses#index'
  patch 'mark_reviewed/:id' => 'static#mark_reviewed', as: 'mark_reviewed'
  get 'design_test' => 'static#design_test'
  get 'new_business' => 'businesses#new_business'
  post 'new_business' => 'businesses#create_business'
  get 'new_complaint' => 'inspections#new_complaint'
  post 'new_complaint' => 'inspections#create_complaint'
  get 'new_permit_inspection' => 'inspections#new_permit_inspection'
  post 'new_permit_inspection' => 'inspections#create_permit_inspection'
  get 'new_license_inspection' => 'inspections#new_license_inspection'
  post 'new_license_inspection' => 'inspections#create_license_inspection'
  get 'unassigned_inspections' => 'inspections#unassigned_inspections'
  get 'assign_inspection/:id' => 'inspections#assign_inspection', as: 'assign_inspection'
  patch 'update_inspector/:id' => 'inspections#update_inspector', as: 'update_inspector'
  get 'inspection_calendar' => 'inspections#inspection_calendar'
  get 'new_business_violation/:business_id' => 'violations#new_business_violation', as: 'new_business_violation'
  get 'all_licenses' => 'licenses#index'
  get 'all_permits' => 'permits#index'
  get 'map' => 'static#map'
  get 'export_violations' => 'violations#export_csv'
  get 'export_property_csv' => 'violations#export_property_csv'
  patch 'inspections/:id/mark_as_paid', to: 'inspections#mark_as_paid', as: :mark_as_paid
  patch 'inspections/:id/mark_as_not_paid', to: 'inspections#mark_as_not_paid', as: :mark_as_not_paid
  post 'create_unit' => 'inspections#create_unit'

  resources :users, only: [:index, :show, :edit, :update]
  resources :notifications do
    member do
      patch :mark_as_read
    end
    collection do
      patch :mark_all_as_read
    end
  end

  authenticated :user, ->(u) { u.admin? } do
    root 'static#admin', as: :admin_root
  end
  unauthenticated do
    root 'static#issue', as: :unauthenticated_root
  end
  root 'static#dashboard'
  get "sir" => "violations#sir"
  get 'my_citations' => 'citations#my_citations'
  get 'all_citations' => 'citations#all_citations'
  get 'admin_user' => 'static#admin_user'
  put "/update_user/:id", to: "static#update_user", as: "update_user"

  namespace :api do
    namespace :v1 do
      resources :addresses do
        member do
          get 'photos'
          get 'violations'
          get 'inspections'
          get 'complaints'
          get 'comments'
        end
      end
      resources :businesses
      resources :complaints
      resources :inspections
      resources :violations
      resources :codes
      resources :contacts
    end
  end
  mount ServiceWorker::Engine => "/service-worker.js"
end

app/models/violation.rb
class Violation < ApplicationRecord
  belongs_to :address
  has_many :violation_codes, dependent: :destroy
  has_many :codes, through: :violation_codes
  belongs_to :user
  validate :at_least_one_code_selected
  has_many_attached :photos
  validates :violation_type, presence: true
  has_many :citations
  belongs_to :unit, optional: true
  has_many :violation_comments, dependent: :destroy
  belongs_to :business, optional: true

  scope :created_within, -> (range) { where(created_at: range) }
  scope :warnings_created_within, -> (range) { created_within(range).where(violation_type: "Doorhanger") }
  scope :violations_created_within, -> (range) { created_within(range).where(violation_type: "Formal Notice") }



  def at_least_one_code_selected
    errors.add(:base, "Please select at least one code") if codes.none?
  end
  
  enum status: [:current, :resolved]

  after_initialize :set_default_status, if: :new_record?

  scope :recent, -> { order(created_at: :desc) }
  
  DEADLINE_OPTIONS = [
    "Immediate",
    "1 day",
    "3 days",
    "7 days",
    "14 days",
    "30 days"
  ]

  DEADLINE_VALUES = [0, 1, 3, 7, 14, 30]

  def deadline_passed?
    deadline_index = DEADLINE_OPTIONS.index(deadline)
    return false if deadline_index.nil?
    created_at + DEADLINE_VALUES[deadline_index].days + extend.days < Time.now
  end

  def deadline_date
    deadline_index = DEADLINE_OPTIONS.index(deadline)
    return false if deadline_index.nil?
    deadline_value = DEADLINE_VALUES[deadline_index]
    if deadline_value.nil?
      raise "Custom deadline value not supported"
    else
      created_at + deadline_value.days + extend.days
    end
  end

  validates :deadline, presence: true, inclusion: { in: DEADLINE_OPTIONS }
  
  
  private

  def set_default_status
    self.status ||= :current
  end
end

app/controllers/api/v1/violations_controller.rb
class Api::V1::ViolationsController < ActionController::Base
  def index
    @violations = Violation.order(created_at: :desc)
    render json: @violations.map { |violation| violation.attributes.merge(address: violation.address) }
  end

  def show
    @violation = Violation.find(params[:id])
    render json: @violation
  end

  def create
    # Your code for creating a new business goes here
  end

  def update
    # Your code for updating an existing business goes here
  end

  def destroy
    # Your code for deleting a business goes here
  end
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController
  before_action :set_address, except: [:sir, :show, :edit, :update]
  before_action :set_violation, only: [:resolve, :extender, :update, :edit]
  layout 'choices', only: [:new, :edit, :new_business_violation]
  before_action :require_ons_or_admin, except: [:sir, :violist]
  before_action :authenticate_user!

  def new
    @violation = @address.violations.new

    @violation.code_ids = params[:code_ids].split(',') if params[:code_ids].present?

    # If the violation is for a unit
    @unit = Unit.find(params[:unit_id]) if params[:unit_id].present?
  end

  def new_business_violation
    @business = Business.find(params[:business_id])
    @address = @business.address
    @violation = @business.violations.new
  end

  def update
    @new_violation = @address.violations.new(violation_params)
    @new_violation.user = current_user

    if @new_violation.save
      @violation.update(status: :resolved)
      redirect_to address_path(@address), notice: "Violation created successfully"
    else
      render :edit
    end
  end

  def violist
    @status = params[:status]
    @user = params[:user]
    @violations = Violation.all
  
    case @status
    when "current"
      @violations = @violations.where(status: :current)
    when "resolved"
      @violations = @violations.where(status: :resolved)
    end
  
    case @user
    when "current_user"
      @violations = @violations.where(user: current_user)
    when "current_user_current"
      @violations = @violations.where(user: current_user, status: :current)
    when "current_user_resolved"
      @violations = @violations.where(user: current_user, status: :resolved)
    end
  
    @violations = @violations.order(created_at: :desc)
  
    @violations = @violations.paginate(page: params[:page], per_page: 15)
  end

  # For the MPIA request
  def export_csv
    @violations = Violation.where('created_at >= ?', 6.months.ago)

    respond_to do |format|
      format.csv { send_data generate_csv(@violations), filename: "violations-#{Date.today}.csv" }
    end
  end

  def export_property_csv
    # Ensure @address is set correctly
    puts "@address: #{@address.inspect}"

    # Get all violations for the address
    @violations = @address.violations

    # Debug output to check if violations are fetched correctly
    puts "@violations: #{@violations.inspect}"

    respond_to do |format|
      format.csv { send_data generate_property_csv(@violations), filename: "#{@address.property_name_with_combadd} violations-#{Date.today}.csv" }
    end
  end

  def edit
  end

  def show 
    @violation = Violation.find(params[:id])
    @address = @violation.address
    @address_citations = @address.violations.map(&:citations).flatten
    @unit = @violation.unit
    @address_photos = (
                        @address.violations.map(&:photos) +
                        @address.comments.map(&:photos) + 
                        @address_citations.map(&:photos)
                      ).flatten.sort_by(&:created_at).reverse
  end

  def sir 
    if params[:start_date].present? && params[:end_date].present?
      start_date = Date.parse(params[:start_date]).beginning_of_day
      end_date = Date.parse(params[:end_date]).end_of_day
      range = start_date..end_date
    else
      # Default to the last 2 weeks
      range = 2.weeks.ago.beginning_of_day..Time.zone.now.end_of_day
    end
  
    @complaints_made = Inspection.complaints_created_within(range)
    @complaint_responses = Inspection.complaint_responses_created_within(range)
    @warnings = Violation.warnings_created_within(range)
    @violations = Violation.violations_created_within(range)
    @citations = Citation.created_within(range)
    @sf_inspections = Inspection.sf_inspections_created_within(range)
    @sf_inspections_updated = Inspection.sf_inspections_updated_within(range)
    @sf_inspections_approved = Inspection.sf_inspections_approved_within(range)
    @mf_inspections = Inspection.mf_inspections_created_within(range)
    @mf_inspections_updated = Inspection.mf_inspections_updated_within(range)
    @mf_inspections_approved = Inspection.mf_inspections_approved_within(range)
    @bl_inspections = Inspection.bl_inspections_created_within(range)
    @bl_inspections_updated = Inspection.bl_inspections_updated_within(range)
  end

  def create
    @violation = @address.violations.new(violation_params)
    @violation.user = current_user

    if @violation.save && @violation.unit.present?
      redirect_to address_unit_path(@violation.address, @violation.unit), notice: "Violation reported successfully."
    elsif @violation.save
      redirect_to @address, notice: "Violation reported successfully."
    else
      render :new
    end
  end

  def resolve
    if @violation.update(status: :resolved)
      redirect_to @violation.address, notice: "Violation resolved successfully."
    else
      redirect_to @violation.address, alert: "Failed to resolve violation."
    end
  end

  def extend_deadline
    @violation = Violation.find(params[:id])
  end

  def update_deadline
    days = params[:days].to_i
    @violation.extend += days
    if @violation.save
      @violation.reload
      redirect_to @violation, notice: "Extended by #{days} days"
    else
      redirect_to @violation, alert: "Failed to extend"
    end
  end

  def generate_report
    @violation = Violation.find(params[:id])
    template_path = "#{Rails.root}/lib/templates/violation_report.docx"
    template = Sablon.template(File.expand_path(template_path))
  
    today = Time.zone.now.strftime("%B %d, %Y")

    # Format the date string
    formatted_date = @violation.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y")
  
    # Replace the placeholders in the document with the data
    rendered_template = template.render_to_string(
      {
        violation: {
          created_at: formatted_date,
          today: today,
          deadline_date: @violation.deadline_date.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y"),
          username: @violation.user.name,
          userphone: @violation.user.phone,
          violation_codes: @violation.violation_codes
        },
        address: {
          combadd: @violation.address.combadd.titleize,
          premisezip: @violation.address.premisezip,
          ownername: @violation.address.ownername.titleize,
          owneraddress: @violation.address.owneraddress.titleize,
          ownercity: @violation.address.ownercity.titleize,
          ownerstate: @violation.address.ownerstate,
          ownerzip: @violation.address.ownerzip
        }
        # Add more data here as needed
      }
    )
  
    # Write the generated file to disk
    output_path = "#{Rails.root}/tmp/violation_report.docx"
    File.open(output_path, "wb") do |f|
      f.write(rendered_template)
    end

    # Format the address and today's date for the filename
    formatted_address = @address.combadd.gsub(/[^\w\s-]/, '').gsub(/[\s]/, '_')
    formatted_date = Time.zone.now.strftime("%Y-%m-%d")
    filename = "violation_notice_#{formatted_address}_#{formatted_date}.docx"
    
    # Send the generated file as a download with the custom filename
    send_file(output_path, filename: filename, type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
  end

  private

  def set_address
    if params[:address_id].present?
      @address = Address.find(params[:address_id])
      if params[:unit_id].present?
        @unit = Unit.find(params[:unit_id])
      end
    elsif params[:id].present?
      @violation = Violation.find(params[:id])
      @address = @violation.address
    end
  end  

  def violation_params
    params.require(:violation).permit(:business_id, :description, :deadline, :status, :extend, :violation_type, :unit_id, photos: [], code_ids: [])
  end

  def set_violation
    @violation = Violation.find(params[:id])
    @address = @violation.address
  end

  def require_ons_or_admin
    unless current_user&.ons? || current_user&.admin?
      flash[:alert] = 'You do not have permission to perform this action.'
      redirect_to root_path
    end
  end

  def generate_csv(violations)
    CSV.generate(headers: true) do |csv|
      csv << ["Address", "Created At", "Codes"]

      violations.each do |violation|
        codes = violation.codes.pluck(:name).join(", ")
        csv << [violation.address.property_name_with_combadd, violation.created_at, codes]
      end
    end
  end

  def generate_property_csv(violations)
    CSV.generate(headers: true) do |csv|
      csv << ["Property/unit", "Created At", "Codes"]

      violations.each do |violation|
        codes = violation.codes.pluck(:name).join(", ")
        csv << [
          violation.unit.present? ? violation.unit : violation.address.property_name_with_combadd, 
          violation.created_at, 
          codes
        ]
      end
    end
  end
  
end

app/helpers/violations_helper.rb
module ViolationsHelper
  def unit_options(units)
    options = [["Building", nil]] # Adding "Building" option as the first element
    options += units.map { |unit| [unit.number, unit.id] }
    options
  end
end

app/views/violations/create.html.erb
<h1>Violations#create</h1>
<p>Find me in app/views/violations/create.html.erb</p>

app/views/violations/extend_deadline.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= form_for @violation, url: update_deadline_violation_path(@violation), method: :patch do |f| %>

      <div>
        <p>Current Deadline: <%= @violation.deadline_date.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y") %></p>
      </div>
      <div class="field">
        <%= label_tag :days, "Extend Deadline By (days)" %>
        <%= number_field_tag :days, nil, min: 0, class: "form-control" %>
      </div>
      
      <%= f.submit "Extend Deadline", class: "btn btn-primary" %>
    <% end %>  
  </div>
</div>

app/views/violations/new.html.erb
<div class="container-fluid">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">
      <%= link_to "Home", root_path %>
    </a></li>
    <li class="breadcrumb-item">
    <%= link_to @address.property_name_with_combadd, address_path(@address) %>
    </li>
    <% if @unit.present? %>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to "Unit " + @unit.number, address_unit_path(@address, @unit) %>
      </li>
    <% end %>
  </ol>
</nav>
<br>

<div class="row">
  <%= render 'shared/address_info' %>
  <div class="col-md-7 col-xl-8">
  <% if @address.violations.where(status: :current).any? %>
    <div class="card">
      <div class="card-body">
        <h4>Current Violations</h4>
          <ol>
          <% @address.violations.where(status: :current).each do |v| %>
            <li>
              <%= link_to v.violation_type, violation_path(v) %> - <%= v.codes.map(&:name).join(", ") %>
              <br>
              <small class="text-muted">
                <%= v.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y %l:%M %p") %>
              </small>
            </li>
          <% end %>
          </ol>
      </div>
    </div>
  <% end %>
    <div class="card">
      <div class="card-body">
  <h1>Create a Violation</h1>

  <%= form_with(model: [@address, @violation], local: true) do |form| %>

  <% if @violation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@violation.errors.count, "error") %> prohibited this violation from being saved:</h2>

      <ul>
        <% @violation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <!-- if address has units, show unit select -->
    <% if @address.units.any? && !params[:unit_id].present? %>
    <div class="form-group">
      <strong>
        <label for="unit_id">Unit</label>
      </strong>
      <em><p>You can leave blank or select "Building" for a building violation, or select a specific unit.</p></em>
      <%= form.select :unit_id, options_for_select(unit_options(@address.units).sort, @unit), {prompt: "Select Building or Unit"}, class: "form-select" %>    </div>
    <br>
    <br>
    <% elsif @address.units.any? && params[:unit_id].present? %>
          <strong>
        <label for="unit_id">Unit</label>
      </strong>
      <%= form.hidden_field :unit_id, value: params[:unit_id] %>
      <p><%= @unit.number %></p>
    <% end %>

  <div class="form-group">
    <strong><%= form.label :violation_type %></strong>
    <%= form.select :violation_type, options_for_select(['Doorhanger', 'Formal Notice']), {}, class: "form-select" %>
  </div>
    <br>
    <div class="field">
      <strong><%= form.label :deadline %></strong>
      <%= form.select :deadline, Violation::DEADLINE_OPTIONS, {}, class: "form-select" %>
    </div>
    <br>
    <strong>Attachments/Images</strong>
      <%= form.file_field :photos, multiple: true, class: "form-control" %>

    <br>
      <div class="form-group">
      <strong><%= form.label :codes %></strong>
      <em><p>If you don't see the code you're looking for, add the code using this button: <%= link_to "New code", new_code_path, class:"btn btn-outline-primary" %></p></em>
  <% if @violation.codes.any? %>
    <div class="form-group">
      <%= form.collection_check_boxes :code_ids, @violation.codes, :id, :name, class: "form-control" do |cb| %>
        <%= cb.label class: "form-check-label" do %>
          <%= cb.check_box class: "form-check-input" %>
          <%= cb.text %>
        <% end %>
      <% end %>
    </div>
  <% end %>

    <select id="code-select" multiple name="violation[code_ids][]">
      <% Code.not_associated_with_violation(@violation).each do |code| %>
        <option value="<%= code.id %>"><%= code.chapter %>-<%= code.section.split("-").last %> <%= code.name %></option>
      <% end %>
    </select>

    </div>
    <br>
 

    <div class="form-group">
      <%= form.submit "Create Violation", class: "btn btn-primary" %>
    </div>
  <% end %>
      </div>
    </div>
  </div>
</div>
</div>

<script>
  // Function to initialize Choices.js
  function initializeChoices() {
    const codeSelect = new Choices('#code-select', {
      removeItemButton: true,
      searchEnabled: true,
      placeholder: true,
      placeholderValue: 'Select codes',
    });
  }

  // Initialize Choices.js on page load
  document.addEventListener("turbo:load", initializeChoices);
</script>

app/views/violations/show.html.erb
<% content_for :title, @violation.address.property_name_with_combadd %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">
      <%= link_to "Home", root_path %>
    </a></li>
    <li class="breadcrumb-item"><a href="#">
    <% if @violation.unit.present? %>
      <%= link_to @violation.unit.number, address_unit_path(@address, @unit) %>
    <% end %>
    <%= link_to @address.property_name_with_combadd, address_path(@address) %>
    </a></li>
    <li class="breadcrumb-item active">
      <%= "Violation ##{params[:id]}" %>
    </li>
  </ol>
</nav>

<div class="row">
  <%= render 'shared/address_info' %>
  <div class="col-md-7 col-xl-8">
    <div class="card shadow mb-3">
      <div class="card-body">         
        <h1>Violation #<%= @violation.id %>
        <% if @violation.business.present? %>
          -
          <%= link_to address_business_path(@address, @violation.business) do %>
             <%= @violation.business.business_name_and_trading_name %>
          <% end %>
        <% end %>
        </h1>
        <p><strong>Violation Type:</strong> <%= @violation.violation_type %></p>
        <p><strong>Violation Date:</strong> <%= @violation.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y") %></p>
        <p><strong>Deadline:</strong> <%= @violation.deadline_date.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y") %></p>

        <%= link_to 'Extend Deadline', extend_deadline_violation_path(@violation), class: 'btn btn-secondary' %>

        <br>
        <br>
      </div>
      <div class="card-body">
        <strong>Codes in Violation:</strong>
        <% @violation.codes.each do |code| %>
          <%= render partial: 'shared/code_def_show', locals: { code: code } %>
        <% end %>
        <% if @violation.photos.attached? %>
        <br>
        <button type="button" class="btn btn-outline-primary btn-lg mt-3" data-bs-toggle="modal" data-bs-target="#allphotoModal">
          Attachments
        </button>
        <% end %>
        <% if @violation.current? %>
        <%= button_to "Mark as Abated", resolve_violation_path(@violation), method: :patch, class: "btn btn-success mb-3 mt-3" %>
        <% if @violation.violation_type == "Formal Notice"%>
          <%= link_to "Generate VN Letter", generate_report_violation_path(@violation), class: "btn btn-primary mb-3" %>
        <% end %>
        <% if @violation.deadline_passed? and @violation.violation_type == "Doorhanger" %>
          <%= link_to "Update to VN", edit_violation_path(@violation), class: "btn btn-warning mb-5" %>
        <% end %>
        <% else %>
        <br>
          <p><strong>Status: </strong>Closed <%= @violation.updated_at.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y") %></p>
        <% end %>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h3>New Comment on Violation</h3>

        <% if user_signed_in? %>
          <%= form_for([@violation, @violation.violation_comments.build]) do |f| %>
            <%= f.text_area :content, class: "form-control" %>
            <br>
            <%= f.file_field :photos, multiple: true, class: "form-control" %>
            <br>
            <%= f.submit class: "btn btn-primary" %>
          <% end %>
        <% end %>

        <!-- show any associated comments -->
        <% if @violation.violation_comments.exists? %>
        <br>
          <h3>Comments (<%= @violation.violation_comments.count %>)</h3>
          <% @violation.violation_comments.order(created_at: :desc).each do |comment| %>
            <%= render 'comments/comments2', comment: comment, show_address_info: false, show_edit_link: true, show_unit_info: false %>
          <% end %>
        <% end %>      
      </div>  
    </div>
          <% if @violation.deadline_passed? && @violation.violation_type == "Formal Notice" %>
    <div class="card">
      <div class="card-body">
        <div class="table-responsive mt-5" style="text-align: center">
          <h1>Citations</h1>
          <%= link_to "New Citation", new_violation_citation_path(@violation), class: "btn btn-danger" %>
            <% if @violation.citations.any? %>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">Citation ID</th>
                    <th scope="col">Status</th>
                    <th scope="col">Code</th>
                    <th scope="col">Deadline</th>
                  </tr>
                </thead>
                <tbody>
                  <% @violation.citations.each do |citation| %>
                    <%= render partial: 'shared/citation_table2', locals: { citation: citation } %>
                  <% end %>
                </tbody> 
              </table>
            <% end %>
        </div>
      </div>
    </div>
          <% end %>
  </div>
</div>



<div class="modal fade custom-modal-lg" id="allphotoModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        All Attachments
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <% @violation.photos.each do |photo| %>
        <%= render partial: 'shared/show_image', locals: { photo: photo } %>
      <% end %>
    </div>
  </div>
</div>