config/routes.rb
Rails.application.routes.draw do
  resources :codes
  resources :rooms do
    resources :prompts
  end
  resources :contacts do
    resources :contact_comments
    member do
      get 'add_notes'
      patch :hide
    end
  end
  devise_for :users
  resources :addresses do
    resources :violations, shallow: true do
      resources :citations, shallow: true do
        resources :citation_comments
      end
      member do
        get :extend_deadline
        patch :update_deadline
        get :units
      end
      patch :resolve, on: :member
      patch :update, on: :member
      get :generate_report, on: :member
      resources :violation_comments
      collection do
        get :export_csv
      end
    end
    resources :comments
    resources :concerns, only: [:create, :edit, :update]
    resources :units, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      member do
        get 'new_unit_business', to: 'businesses#new_unit_business'
        get 'all_unit_comments'
        get 'all_unit_violations'
        get 'all_unit_citations'
        get 'all_unit_inspections'
        get 'all_unit_complaints'
        get 'manage_contacts'
        post 'manage_contacts'
        delete 'remove_contact'
        get :set_potentially_vacant
        get :set_vacant
        get :set_occupied
      end
    end
    resources :inspections do
      member do
        get 'conduct'
        get 'schedule'
        post 'save_and_redirect_to_area_new'
        get 'create_business_license'
        get 'create_single_family_license'
        get 'create_multifamily_license'
        get 'create_permit'
      end
      resources :areas do
        resources :observations, only: [:create, :edit, :update]
      end
      resources :inspection_comments
      resources :licenses, except: [:index]
    end
    resources :businesses, except: [:index, :new_business]
    member do
      get 'manage_contacts'
      post 'manage_contacts'
      delete 'remove_contact'
      get 'address_name'
      get 'all_address_violations'
      get 'all_address_comments'
      get 'all_address_citations'
      get 'all_address_inspections'
      get 'all_address_complaints'
      get 'add_aka'
      get :set_potentially_vacant
      get :set_vacant
      get :set_occupied
      get :set_registered
    end
    collection do
      get :potentially_vacant
      get :vacant
    end
  end

  resources :licenses do
    get 'email_license' => 'licenses#email_license'
    get 'download_license' => 'licenses#download_license'
    member do
      put 'sent_today' => 'licenses#sent_today' 
      put 'not_sent' => 'licenses#not_sent'
      put 'paid' => 'licenses#paid'
      put 'not_paid' => 'licenses#not_paid'
      get 'generate_business'
      get 'generate_single_family'
    end
  end

  resources :permits do
    member do
      put 'sent' => 'permits#sent'
      put 'revoked' => 'permits#revoked'
      put 'paid' => 'permits#paid'
    end
  end

  get 'all_inspections' => 'inspections#all_inspections'
  get 'my_inspections' => 'inspections#my_inspections'
  get 'my_unscheduled_inspections' => 'inspections#my_unscheduled_inspections'
  get 'all_complaints' => 'inspections#all_complaints'
  get 'my_complaints' => 'inspections#my_complaints'
  get 'all_violations' => 'violations#violist'
  get 'my_violations' => 'addresses#my_violations'
  get 'helpful' => 'static#helpful'
  get 'businesses' => 'businesses#index'
  patch 'mark_reviewed/:id' => 'static#mark_reviewed', as: 'mark_reviewed'
  get 'design_test' => 'static#design_test'
  get 'new_business' => 'businesses#new_business'
  post 'new_business' => 'businesses#create_business'
  get 'new_complaint' => 'inspections#new_complaint'
  post 'new_complaint' => 'inspections#create_complaint'
  get 'new_permit_inspection' => 'inspections#new_permit_inspection'
  post 'new_permit_inspection' => 'inspections#create_permit_inspection'
  get 'new_license_inspection' => 'inspections#new_license_inspection'
  post 'new_license_inspection' => 'inspections#create_license_inspection'
  get 'unassigned_inspections' => 'inspections#unassigned_inspections'
  get 'assign_inspection/:id' => 'inspections#assign_inspection', as: 'assign_inspection'
  patch 'update_inspector/:id' => 'inspections#update_inspector', as: 'update_inspector'
  get 'inspection_calendar' => 'inspections#inspection_calendar'
  get 'new_business_violation/:business_id' => 'violations#new_business_violation', as: 'new_business_violation'
  get 'all_licenses' => 'licenses#index'
  get 'all_permits' => 'permits#index'
  get 'map' => 'static#map'
  get 'export_violations' => 'violations#export_csv'
  get 'export_property_csv' => 'violations#export_property_csv'
  patch 'inspections/:id/mark_as_paid', to: 'inspections#mark_as_paid', as: :mark_as_paid
  patch 'inspections/:id/mark_as_not_paid', to: 'inspections#mark_as_not_paid', as: :mark_as_not_paid
  post 'create_unit' => 'inspections#create_unit'

  resources :users, only: [:index, :show, :edit, :update]
  resources :notifications do
    member do
      patch :mark_as_read
    end
    collection do
      patch :mark_all_as_read
    end
  end

  authenticated :user, ->(u) { u.admin? } do
    root 'static#admin', as: :admin_root
  end
  unauthenticated do
    root 'static#issue', as: :unauthenticated_root
  end
  root 'static#dashboard'
  get "sir" => "violations#sir"
  get 'my_citations' => 'citations#my_citations'
  get 'all_citations' => 'citations#all_citations'
  get 'admin_user' => 'static#admin_user'
  put "/update_user/:id", to: "static#update_user", as: "update_user"

  namespace :api do
    namespace :v1 do
      resources :addresses do
        member do
          get 'photos'
          get 'violations'
          get 'inspections'
          get 'complaints'
          get 'comments'
        end
      end
      resources :businesses
      resources :complaints
      resources :inspections
      resources :violations
      resources :codes
      resources :contacts
    end
  end
  mount ServiceWorker::Engine => "/service-worker.js"
end

app/models/inspection.rb
class Inspection < ApplicationRecord
  belongs_to :unit, optional: true
  belongs_to :address
  has_many :violations, dependent: :destroy
  belongs_to :user, optional: true
  has_many_attached :attachments
  has_many_attached :photos
  has_many_attached :intphotos
  has_many_attached :extphotos
  belongs_to :assignee, class_name: "User", foreign_key: "assignee_id", optional: true
  belongs_to :inspector, class_name: "User", optional: true
  has_many :inspection_codes
  has_many :codes, through: :inspection_codes
  belongs_to :contact, optional: true
  has_many :areas, dependent: :destroy
  belongs_to :business, optional: true
  has_many :inspection_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_one :license, dependent: :destroy
  has_one :permit, dependent: :destroy
  has_paper_trail

  after_update :update_license_paid_status, if: :saved_change_to_paid?

  scope :created_within, -> (range) { where(created_at: range) }
  scope :updated_within, -> (range) { where(updated_at: range) }
  scope :complaints_created_within, -> (range) { created_within(range).where(source: "Complaint") }
  scope :complaint_responses_created_within, -> (range) { complaints_created_within(range).where.not(status: nil) }
  scope :sf_inspections_created_within, -> (range) { created_within(range).where(source: "Single Family License", status: ["Satisfactory", "Unsatisfactory"]) }
  scope :sf_inspections_updated_within, -> (range) { updated_within(range).where(source: "Single Family License") }
  scope :sf_inspections_approved_within, -> (range) { sf_inspections_updated_within(range).where(status: "Satisfactory") }
  scope :mf_inspections_created_within, -> (range) { created_within(range).where(source: "Multifamily License") }
  scope :mf_inspections_updated_within, -> (range) { updated_within(range).where(source: "Multifamily License") }
  scope :mf_inspections_approved_within, -> (range) { mf_inspections_updated_within(range).where(status: "Satisfactory") }
  scope :bl_inspections_created_within, -> (range) { created_within(range).where(source: "Business license") }
  scope :bl_inspections_updated_within, -> (range) { updated_within(range).where(source: "Business license") }

  attr_accessor :current_user

  after_create :create_notification_if_complaint
  after_update :create_notification_if_reassigned

  # define a completed inspection
  def completed?
    status.present?
  end

  private

  def create_notification_if_complaint
    Rails.logger.info "Checking for complaint inspection..."
    return unless source == 'Complaint' && inspector.id != current_user.id
    Rails.logger.info "Inspection is a complaint."
    notification = Notification.create(
      inspection: self,
      user: inspector,
      title: "New Complaint Inspection for #{address.property_name_with_combadd}",
      body: "You have been assigned a new complaint inspection for #{address.property_name_with_combadd}."
    )
    NotificationMailer.notify_inspector(notification).deliver_later if notification.persisted?
    Rails.logger.info "Notification created."
  rescue => e
    Rails.logger.error "Error in create_notification_if_complaint: #{e.message}"
  end

  def create_notification_if_reassigned
    Rails.logger.info "Checking for inspection reassignment..."
    if saved_change_to_inspector_id? && inspector != current_user
      Rails.logger.info "Inspector has been reassigned."
      notification = Notification.create(
        inspection: self,
        user: inspector,
        title: "Inspection Assignment",
        body: "You have been assigned to an inspection at #{address.property_name_with_combadd}."
      )
      if notification.persisted?
        NotificationMailer.notify_inspector(notification).deliver_later
        Rails.logger.info "Notification successfully created"
      else
        Rails.logger.error "Failed to create notification: #{notification.errors.full_messages}"
      end
    else
      Rails.logger.info "Inspector has not been reassigned."
    end
  rescue => e
    Rails.logger.error "Error in create_notification_if_reassigned: #{e.message}"  
  end

  def no_inspection_within_one_hour
    if scheduled_datetime.present?
      # Check if there are any other inspections scheduled within 1 hour
      if Inspection.where(inspector_id: inspector_id, status: nil)
                  .where('scheduled_datetime >= ? AND scheduled_datetime <= ?', scheduled_datetime - 1.hour, scheduled_datetime + 1.hour)
                  .where.not(id: id) # Exclude the current inspection if it's being updated
                  .exists?
        errors.add(:scheduled_datetime, "Another inspection is scheduled within 1 hour of this time.")
        throw :abort # Prevent saving if there is an error
      end
    end
  end

  def scheduled_datetime_cannot_be_in_the_past
    if scheduled_datetime.present? && scheduled_datetime < DateTime.now
      errors.add(:scheduled_datetime, "can't be in the past")
    end
  end

  def no_inspections_within_30_minutes
    return unless scheduled_datetime

    # Define the time range
    time_range = (scheduled_datetime - 30.minutes)..(scheduled_datetime + 30.minutes)

    # Check for any inspections within this range
    if Inspection.where.not(id: id).where(scheduled_datetime: time_range).exists?
      errors.add(:scheduled_datetime, 'is too close to another inspection')
    end
  end

  def update_license_paid_status
    license.update(paid: self.paid) if license && license.paid != self.paid
  end
end

app/controllers/api/v1/inspections_controller.rb
class Api::V1::InspectionsController < ActionController::Base
  def index
    @inspections = Inspection.all
    render json: @inspections.map { |inspection| inspection.attributes.merge(address: inspection.address) }
  end

  def show
    @inspection = Inspection.find(params[:id])
    render json: @inspection
  end

  def create
    # Your code for creating a new business goes here
  end

  def update
    # Your code for updating an existing business goes here
  end

  def destroy
    # Your code for deleting a business goes here
  end
end

app/helpers/inspections_helper.rb
module InspectionsHelper
  def assignee_options(selected_assignee)
    users = User.ons.order(:email)
    options = [["Unassigned", nil]] # Adding "Unassigned" option as the first element
    options += users.pluck(:email, :id)
    options_for_select(options, selected_assignee)
  end

  def generate_pre_inspection_email_link
    if @inspection.scheduled_datetime.present?
      recipient_email = @inspection.contact.email
      subject = "Pre-Inspection Notification for #{@inspection.source.titleize}"
      body = "Hello, 
      
      This is a pre-inspection notification.

      You are receiving this email to inform you #{@inspection.address.property_name_with_combadd} has been scheduled for its annual inspection on #{@inspection.scheduled_datetime.strftime('%m/%d/%Y')} between the hours of #{@inspection.scheduled_datetime.strftime('%I:%M%p')} - #{(@inspection.scheduled_datetime + 1.hour).strftime('%I:%M%p')}.      I look forward to our collaboration and thank you for your role in ensuring life and safety in Riverdale Park.
      
      During the inspection, the property will be evaluated for compliance with Town codes and ordinances. For more information on the Town’s codes and ordinances, please visit the Town’s website at www.riverdaleparkmd.gov.

      Should you have questions or concerns please reply to this email. Lastly, please confirm your receipt of this email.
      
      Best Regards,
      
      #{current_user.name}
      #{current_user.phone}
      #{current_user.email}"
    
      mail_to(recipient_email, subject: subject, body: body, class: "btn btn-secondary") do
        # Customize the button text here
        "Pre inspection email"
      end
    else
      receipient_email = @inspection.contact.email
      subject = "Pre-Inspection Notification for #{@inspection.source.titleize}"
      body = "Hello, 
      This is a pre-inspection notification.
      
      You are receiving this email to inform you that #{@inspection.address.property_name_with_combadd} is pending an inspection for #{@inspection.source.titleize}. The inspection date and time have not yet been scheduled. We will notify you as soon as the inspection is scheduled.
      
      I look forward to our collaboration and thank you for your role in ensuring life and safety in Riverdale Park.
      
      During the inspection, the property will be evaluated for compliance with Town codes and ordinances. For more information on the Town’s codes and ordinances, please visit the Town’s website at www.riverdaleparkmd.gov.
      
      Should you have questions or concerns, please reply to this email. Lastly, please confirm your receipt of this email.
      
      Best Regards,
      
      #{current_user.name}
      #{current_user.phone}
      #{current_user.email}"
      

      mail_to(recipient_email, subject: subject, body: body, class: "btn btn-secondary") do
        # Customize the button text here
        "Pre inspection email"
      end
    end
  end

  def generate_inspection_email_link
    inspection = @inspection
    recipient_email = @inspection.contact.email
    subject = "Inspection Result for #{inspection.source.titleize}"
    body = "
    Hello,

    We are writing to inform you that the annual inspection for #{inspection.address.property_name_with_combadd} has been completed#{'. The inspection was conducted on ' if inspection.scheduled_datetime.present?}#{inspection.scheduled_datetime.strftime('%m/%d/%Y') if inspection.scheduled_datetime.present?}.

    Inspection Status: #{inspection.status}
    #{'Congratulations, your property has passed the inspection. We appreciate your cooperation and thank you for your role in ensuring life and safety in Riverdale Park.' if inspection.status == 'Satisfactory'}
    #{'Unfortunately, your property did not pass the inspection. Please see the attached report for details on the areas that require attention. For a detailed report, please refer to the attached inspection document. For more information on the Town’s codes and ordinances, please visit the Town’s website at www.riverdaleparkmd.gov.' if inspection.status == 'Unsatisfactory'}
    #{'' if inspection.status == 'Unsatisfactory'}

    #{'Inspection Codes: ' + inspection.code_ids.join(', ') if inspection.code_ids.present?}


    Should you have questions or concerns, please reply to this email.

    Best Regards,

    #{current_user.name}
    #{current_user.phone}
    #{current_user.email}
    "
    mail_to(recipient_email, subject: subject, body: body, class: "btn btn-primary") do
      # Customize the button text here
      "Inspection result email"
    end
  end

  def business_options(businesses)
    options = []
    options << ["No Business", nil]
    options += businesses.pluck(:name, :id)
    options_for_select(options)
  end
end

app/views/inspections/all_complaints.html.erb
<!-- inspection table -->

<div class="row">
  <div class="col">
    <div class="card">
      <div class="text-center mt-3 mb-3">
        <h2>Complaints</h2>
        <a class="btn dropdown-toggle d-sm-inline-block" href="#" data-bs-toggle="dropdown">
          <span class="text-dark">Filter</span>
          </span>
        </a>
        <div class="dropdown-menu">
          <%= link_to "All Complaints", all_complaints_path, class:"dropdown-item" %>
          <% if current_user.ons? %>
            <%= link_to "My Complaints", all_complaints_path(inspector: "My Complaints"), class:"dropdown-item" %>      
            <%= link_to "My Pending Complaints", all_complaints_path(inspector: "My Complaints", status: "Pending"), class: "dropdown-item" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Complaints (<%= @inspections.count %>)</h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="table-responsive">
          <table id="example2" class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">Address</th>
                <th scope="col">Created At</th>
                <th scope="col">Source</th>
                <th scope="col">Status</th>
                <th scope="col">Inspector</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @inspections.order("created_at DESC").each do |inspection| %>
                <%= render partial: "shared/complaint_table2", locals: {inspection: inspection} %>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @inspections, class:"text-center" %>
        </div>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  <!-- /.col -->
</div>

app/views/inspections/assign_inspection.html.erb
<%= @inspection.address.property_name_with_combadd %>

<%= @inspection.created_at.strftime("%B %d, %Y %I:%M %p") %>

<%= @inspection.source %>

<!-- form for inspection inspector -->
<%= form_with model: @inspection, url: update_inspector_path(@inspection), method: :patch do |f| %>
  <%= f.select :inspector_id, options_for_select([["Unassigned", nil]] + User.ons.map { |user| [user.email, user.id] }, @inspection.inspector_id), {}, class: "form-select" %>
  <%= f.submit "Assign", class: "btn btn-outline-primary" %>
<% end %>

app/views/inspections/edit.html.erb
<h1>Conduct Inspection</h1>

<%= form_with(model: [@address, @inspection]) do |form| %>
  <div class="form-group mt-3">
    <%= form.label :inspector_id %>
    <%= form.select :inspector_id, options_for_select([["Unassigned", nil]] + User.ons.map { |user| [user.email, user.id] }), {}, class: "form-select" %>
  </div>
  <div class="form-group mt-3">
    <%= form.label :source %>
    <%= form.select :source, ["Complaint", "Building/Dumpster/POD permit", "Business license", "Single Family License", "Multifamily License", "Donation Bin"], {}, class: "form-select" %>
  </div>
  <div class="actions mt-3">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/inspections/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">
      <%= link_to "Home", root_path %>
    </a></li>
    <li class="breadcrumb-item"><a href="#">
    <%= link_to @address.property_name_with_combadd, address_path(@address) %>
    </a></li>

    <% if @unit.present? %>
      <li class="breadcrumb-item"><a href="#">
      <%= link_to @unit.number, address_unit_path(@address, @unit) %>
      </a></li>
    <% end %>
  </ol>
</nav>


<h2>Create New Inspection Request</h2>
<h4><%= @address.property_name_with_combadd %></h4>
<p>* fields are mandatory</p>

<%= form_with(model: [@address, @inspection]) do |form| %>

   <!-- if address has units, show unit select -->
    <% if @address.units.any? && !params[:unit_id].present? %>
    <div class="form-group">
      <strong>
        <label for="unit_id">Unit</label>
      </strong>
      <em><p>You can leave blank or select "Building" for a building violation, or select a specific unit.</p></em>
      <%= form.select :unit_id, options_for_select(unit_options(@address.units).sort, @unit), {prompt: "Select Building or Unit"}, class: "form-select" %>    </div>
    <br>
    <br>
    <% elsif @address.units.any? && params[:unit_id].present? %>
          <strong>
        <label for="unit_id">Unit</label>
      </strong>
      <%= form.hidden_field :unit_id, value: params[:unit_id] %>
      <p><%= @unit.number %></p>
    <% end %>

  <div class="field mt-3">
    <%= form.label :source %>*
    <%= form.select :source, ["Complaint", "Building/Dumpster/POD permit", "Business license", "Single Family License", "Multifamily License", "Donation Bin"], {}, class: "form-select" %>
  </div>

  <div class="field mt-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field mt-3">
    <label>
    Application or photos
    </label>
      <%= form.file_field :attachments, multiple: true, class: "form-control" %>
  </div>




  <% if @inspection.business.present? %>
  <label>Business: </label>
    <strong>
      <%= @inspection.business.business_name_and_trading_name %>
    </strong>
    <%= form.hidden_field :business_id, value: @inspection.business.id %>
  <% else %>
    <% if @address.businesses.exists? || @address.units.joins(:businesses).exists? %>
    <div class="field mt-3">
      <label>Select if the inspection is for a business in the building</label>
      <%= form.select :business_id, options_for_select(business_options(@address.businesses), nil), {prompt: "Select Business"}, class: "form-select" %>
    </div>
    <% end %>
  <% end %>
  
  <div class="field mt-3">
    <%= form.label :scheduled_datetime %>
    <%= form.datetime_field :scheduled_datetime, class: "form-control" %>
  </div>
  

  <div class="form-group mt-3">
    <%= form.label :contact_id %>
    <%= form.collection_select(:contact_id, Contact.all, :id, :full_name_and_email, { prompt: 'Select or create a contact' }, class: 'form-control selectpicker', data: { style: 'btn-primary' }) %>
  </div>

  <!-- Fields for creating a new contact -->

  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          Or create a new contact
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
          <div class="field mt-3">
            <%= form.label :new_contact_name %>
            <%= form.text_field :new_contact_name, class: "form-control" %>
          </div>

          <div class="field mt-3">
            <%= form.label :new_contact_email %>
            <%= form.text_field :new_contact_email, class: "form-control" %>
          </div>

          <div class="field mt-3">
            <%= form.label :new_contact_phone %>
            <%= form.text_field :new_contact_phone, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="form-group mt-3">
    <% if current_user.role == "ons" %>
        <%= form.label :inspector_id %>
      <strong><%= current_user.name %></strong>
      <%= form.hidden_field :inspector_id, value: current_user.id %>
    <% elsif current_user.role == "admin" %>
        <%= form.label :inspector_id %>
      <%= form.select :inspector_id, options_for_select([["Unassigned", nil]] + User.ons.map { |user| [user.email, user.id] }), {}, class: "form-select" %>
      <% else %>
    <% end %>
  </div>

  <!-- form to add whether an inspection is paid or not boolean-->
<div class="form-group mt-3">
  <label for="paid">If the inspection is for a license, has it been paid for?</label>
  <div class="form-check">
    <%= form.check_box :paid, class: "form-check-input" %>
    <%= form.label :paid, class: "form-check-label" %>
  </div>
</div>

  <div class="actions mt-3">
    <%= form.submit "Create Inspection Request", class: "btn btn-primary" %>
  </div>
<% end %>


<script>
  // Function to initialize Choices.js
  function initializeChoices() {
    const contactSelect = new Choices('#inspection_contact_id', {
      removeItemButton: true,
      searchEnabled: true,
      placeholder: true,
      placeholderValue: 'Select a contact',
    });
  }

  // Initialize Choices.js on page load
  document.addEventListener("turbo:load", initializeChoices);
</script>

app/views/inspections/schedule.html.erb
<% if @inspection.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>
    <ul>
      <% @inspection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">
      <%= link_to "Home", root_path %>
    </a></li>
    <li class="breadcrumb-item"><a href="#">
    <%= link_to @address.property_name_with_combadd, address_path(@address) %>
    </a></li>

    <% if @inspection.unit_id.present? %>
      <li class="breadcrumb-item"><a href="#">
      <%= link_to @inspection.unit.number, address_unit_path(@address, @inspection.unit) %>
      </a></li>
    <% end %>

    <li class="breadcrumb-item active"><a href="#">
    <%= link_to "Inspection ##{@inspection.id}", address_inspection_path(@address, @inspection) %>
    </a></li>
  </ol>
</nav>

<h1>Conduct Inspection</h1>
<%= form_with(model: [@address, @inspection]) do |form| %>
  <div class="row">
    <div class="col-md-4">
      <div class="field mt-3">
        <%= form.label :scheduled_datetime %>
        <%= form.datetime_field :scheduled_datetime, class: "form-control" %>
        <% if @inspection.errors[:scheduled_datetime].any? %>
          <p class="text-danger"><%= @inspection.errors[:scheduled_datetime].join(', ') %></p>
        <% end %>
      </div>

      <% if current_user.email.start_with?("rr") %>
      <div class="field mt-3">
        <label>Inspection time confirmed with owner or tenant?</label>
        <br>
        <br>
        <%= form.radio_button :confirmed, true %> Yes
        <%= form.radio_button :confirmed, false %> No
        <% if @inspection.errors[:confirmed].any? %>
          <p class="text-danger"><%= @inspection.errors[:confirmed].join(', ') %></p>
        <% end %>
      </div>
      <% end %>

      <div class="actions mt-3">
        <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>

    </div>
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%# list of scheduled inspections %>
          <% if @scheduled_inspections.present? %>
            <h3>Previously Scheduled Inspections</h3>
            <table class="table table-striped">
              <thead class="thead-light">
                <tr>
                  <th scope="col">Address</th>
                  <th scope="col">Scheduled Date</th>
                  <th scope="col">Scheduled Time</th>
                </tr>
              </thead>
              <tbody>
                <% @scheduled_inspections.each do |inspection| %>
                  <tr>
                    <td><%= inspection.address.property_name_with_combadd %></td>
                    <td><%= inspection.scheduled_datetime.strftime("%m/%d/%Y") %></td>
                    <td><%= inspection.scheduled_datetime.strftime("%I:%M %p") %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <h3>No Scheduled Inspections</h3>
          <% end %>
        </div>
      </div>
    </div>
  </div>


<% end %>